"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { useLocale } from "@/components/layout/LocaleProvider";

const content: Record<string, {
  back: string; title: string; updated: string;
  s1h: string; s1: string;
  s2h: string; s2a: string; s2b: string; s2c: string; s2d: string;
  s3h: string; s3a: string; s3b: string; s3c: string; s3d: string; s3e: string;
  s4h: string; s4p: string; s4a: string; s4b: string; s4c: string; s4end: string;
  s5h: string; s5: string;
  s6h: string; s6: string;
  s7h: string; s7p: string; s7a: string; s7b: string; s7c: string; s7d: string; s7e: string; s7end: string;
  s8h: string; s8: string;
  s9h: string; s9: string;
  s10h: string; s10: string;
}> = {
  en: {
    back: "Back", title: "Privacy Policy", updated: "Last updated: March 2025",
    s1h: "1. Who We Are",
    s1: "Noctirae is an AI-powered dream journaling and interpretation service. By using this service, you agree to the collection and use of information as described in this policy.",
    s2h: "2. What We Collect",
    s2a: "Account information — your email address when you register",
    s2b: "Dream content — the dream descriptions you submit for interpretation",
    s2c: "Usage data — pages visited, features used, session duration",
    s2d: "Payment data — processed by Stripe; we never store your card details",
    s3h: "3. How We Use Your Data",
    s3a: "To provide dream interpretations via AI (OpenAI)",
    s3b: "To save your dream journal and show patterns over time",
    s3c: "To manage your subscription (Stripe)",
    s3d: "To respond to support requests",
    s3e: "To improve the service",
    s4h: "4. Third-Party Services",
    s4p: "We share data with the following trusted services to operate the product:",
    s4a: "Supabase — database and authentication (EU region)",
    s4b: "OpenAI — AI dream interpretation (your dream text is sent to OpenAI for processing)",
    s4c: "Stripe — payment processing",
    s4end: "We do not sell your data to any third parties.",
    s5h: "5. Data Retention",
    s5: "Your data is retained for as long as your account is active. You can delete your account and all associated data at any time from the Settings page. Upon deletion, your data is permanently removed within 30 days.",
    s6h: "6. Cookies",
    s6: "We use only essential cookies necessary for authentication and maintaining your session. We do not use tracking or advertising cookies.",
    s7h: "7. Your Rights (GDPR)",
    s7p: "As an EU resident, you have the right to:",
    s7a: "Access the personal data we hold about you",
    s7b: "Request correction of inaccurate data",
    s7c: "Request deletion of your data (\"right to be forgotten\")",
    s7d: "Object to processing of your data",
    s7e: "Data portability",
    s7end: "To exercise any of these rights, contact us via the Help & Support form in Settings or email noctiraeai@gmail.com.",
    s8h: "8. Security",
    s8: "We take reasonable technical measures to protect your data, including encrypted connections (HTTPS) and secure database storage. However, no internet transmission is 100% secure.",
    s9h: "9. Changes to This Policy",
    s9: "We may update this policy from time to time. We will notify you of significant changes via email or a notice within the app.",
    s10h: "10. Contact",
    s10: "Questions about this policy? Contact us at noctiraeai@gmail.com.",
  },
  lt: {
    back: "Grįžti", title: "Privatumo politika", updated: "Paskutinį kartą atnaujinta: 2025 m. kovas",
    s1h: "1. Kas mes esame",
    s1: "Noctirae yra AI pagrindu veikianti sapnų dienoraščio ir interpretacijos paslauga. Naudodamiesi šia paslauga, jūs sutinkate su informacijos rinkimu ir naudojimu, kaip aprašyta šioje politikoje.",
    s2h: "2. Ką mes renkame",
    s2a: "Paskyros informacija — jūsų el. pašto adresas registruojantis",
    s2b: "Sapnų turinys — sapnų aprašymai, kuriuos pateikiate interpretacijai",
    s2c: "Naudojimo duomenys — aplankyti puslapiai, naudojamos funkcijos, sesijos trukmė",
    s2d: "Mokėjimo duomenys — tvarkomi per Stripe; mes niekada nesaugome jūsų kortelės duomenų",
    s3h: "3. Kaip mes naudojame jūsų duomenis",
    s3a: "Sapnų interpretacijoms teikti per AI (OpenAI)",
    s3b: "Jūsų sapnų dienoraščiui išsaugoti ir modeliams laikui bėgant rodyti",
    s3c: "Jūsų prenumeratai valdyti (Stripe)",
    s3d: "Atsakyti į pagalbos prašymus",
    s3e: "Paslaugai tobulinti",
    s4h: "4. Trečiųjų šalių paslaugos",
    s4p: "Mes dalijamės duomenimis su šiomis patikimomis paslaugomis produktui veikti:",
    s4a: "Supabase — duomenų bazė ir autentifikacija (ES regionas)",
    s4b: "OpenAI — AI sapnų interpretacija (jūsų sapno tekstas siunčiamas OpenAI apdorojimui)",
    s4c: "Stripe — mokėjimų apdorojimas",
    s4end: "Mes neparduodame jūsų duomenų jokioms trečiosioms šalims.",
    s5h: "5. Duomenų saugojimas",
    s5: "Jūsų duomenys saugomi tol, kol jūsų paskyra yra aktyvi. Galite ištrinti paskyrą ir visus susijusius duomenis bet kada iš Nustatymų puslapio. Po ištrynimo jūsų duomenys bus visam laikui pašalinti per 30 dienų.",
    s6h: "6. Slapukai",
    s6: "Mes naudojame tik esminius slapukus, reikalingus autentifikacijai ir sesijos palaikymui. Mes nenaudojame sekimo ar reklaminių slapukų.",
    s7h: "7. Jūsų teisės (BDAR)",
    s7p: "Kaip ES gyventojas, jūs turite teisę:",
    s7a: "Gauti prieigą prie mūsų turimos asmeninės informacijos apie jus",
    s7b: "Prašyti ištaisyti netikslius duomenis",
    s7c: "Prašyti ištrinti jūsų duomenis (\"teisė būti pamirštam\")",
    s7d: "Nesutikti su jūsų duomenų tvarkymu",
    s7e: "Duomenų perkeliamumas",
    s7end: "Norėdami pasinaudoti bet kuria iš šių teisių, susisiekite su mumis per Pagalbos ir palaikymo formą Nustatymuose arba el. paštu noctiraeai@gmail.com.",
    s8h: "8. Saugumas",
    s8: "Mes imamės pagrįstų techninių priemonių jūsų duomenims apsaugoti, įskaitant šifruotus ryšius (HTTPS) ir saugų duomenų bazės saugojimą. Tačiau jokie interneto perdavimai nėra 100% saugūs.",
    s9h: "9. Šios politikos pakeitimai",
    s9: "Mes galime periodiškai atnaujinti šią politiką. Apie reikšmingus pakeitimus jus informuosime el. paštu arba pranešimu programėlėje.",
    s10h: "10. Kontaktai",
    s10: "Turite klausimų dėl šios politikos? Susisiekite su mumis: noctiraeai@gmail.com.",
  },
  de: {
    back: "Zurück", title: "Datenschutzrichtlinie", updated: "Zuletzt aktualisiert: März 2025",
    s1h: "1. Wer wir sind",
    s1: "Noctirae ist ein KI-gestützter Traumtagebuch- und Interpretationsdienst. Durch die Nutzung dieses Dienstes stimmen Sie der Erfassung und Verwendung von Informationen gemäß dieser Richtlinie zu.",
    s2h: "2. Was wir sammeln",
    s2a: "Kontoinformationen — Ihre E-Mail-Adresse bei der Registrierung",
    s2b: "Trauminhalt — Traumbeschreibungen, die Sie zur Interpretation einreichen",
    s2c: "Nutzungsdaten — besuchte Seiten, verwendete Funktionen, Sitzungsdauer",
    s2d: "Zahlungsdaten — verarbeitet von Stripe; wir speichern niemals Ihre Kartendaten",
    s3h: "3. Wie wir Ihre Daten verwenden",
    s3a: "Zur Bereitstellung von Traumdeutungen via KI (OpenAI)",
    s3b: "Zum Speichern Ihres Traumtagebuchs und zur Anzeige von Mustern im Laufe der Zeit",
    s3c: "Zur Verwaltung Ihres Abonnements (Stripe)",
    s3d: "Zur Beantwortung von Supportanfragen",
    s3e: "Zur Verbesserung des Dienstes",
    s4h: "4. Drittanbieter-Dienste",
    s4p: "Wir teilen Daten mit folgenden vertrauenswürdigen Diensten:",
    s4a: "Supabase — Datenbank und Authentifizierung (EU-Region)",
    s4b: "OpenAI — KI-Traumdeutung (Ihr Traumtext wird an OpenAI zur Verarbeitung gesendet)",
    s4c: "Stripe — Zahlungsabwicklung",
    s4end: "Wir verkaufen Ihre Daten nicht an Dritte.",
    s5h: "5. Datenspeicherung",
    s5: "Ihre Daten werden gespeichert, solange Ihr Konto aktiv ist. Sie können Ihr Konto und alle zugehörigen Daten jederzeit über die Einstellungen löschen. Nach der Löschung werden Ihre Daten innerhalb von 30 Tagen dauerhaft entfernt.",
    s6h: "6. Cookies",
    s6: "Wir verwenden nur wesentliche Cookies für Authentifizierung und Sitzungsverwaltung. Wir verwenden keine Tracking- oder Werbe-Cookies.",
    s7h: "7. Ihre Rechte (DSGVO)",
    s7p: "Als EU-Bürger haben Sie das Recht auf:",
    s7a: "Zugang zu Ihren personenbezogenen Daten",
    s7b: "Berichtigung ungenauer Daten",
    s7c: "Löschung Ihrer Daten (\"Recht auf Vergessenwerden\")",
    s7d: "Widerspruch gegen die Datenverarbeitung",
    s7e: "Datenübertragbarkeit",
    s7end: "Kontaktieren Sie uns über das Support-Formular in den Einstellungen oder per E-Mail: noctiraeai@gmail.com.",
    s8h: "8. Sicherheit",
    s8: "Wir ergreifen angemessene Maßnahmen zum Schutz Ihrer Daten, einschließlich HTTPS und sicherer Datenbankspeicherung. Keine Internetübertragung ist jedoch 100% sicher.",
    s9h: "9. Änderungen dieser Richtlinie",
    s9: "Wir können diese Richtlinie aktualisieren. Wesentliche Änderungen teilen wir per E-Mail oder App-Benachrichtigung mit.",
    s10h: "10. Kontakt",
    s10: "Fragen? Schreiben Sie uns: noctiraeai@gmail.com.",
  },
  fr: {
    back: "Retour", title: "Politique de confidentialité", updated: "Dernière mise à jour : mars 2025",
    s1h: "1. Qui nous sommes",
    s1: "Noctirae est un service de journal de rêves et d'interprétation basé sur l'IA. En utilisant ce service, vous acceptez la collecte et l'utilisation des informations décrites dans cette politique.",
    s2h: "2. Ce que nous collectons",
    s2a: "Informations de compte — votre adresse e-mail lors de l'inscription",
    s2b: "Contenu des rêves — les descriptions de rêves que vous soumettez",
    s2c: "Données d'utilisation — pages visitées, fonctionnalités utilisées, durée de session",
    s2d: "Données de paiement — traitées par Stripe ; nous ne stockons jamais vos coordonnées bancaires",
    s3h: "3. Comment nous utilisons vos données",
    s3a: "Pour fournir des interprétations de rêves via l'IA (OpenAI)",
    s3b: "Pour sauvegarder votre journal et afficher les tendances",
    s3c: "Pour gérer votre abonnement (Stripe)",
    s3d: "Pour répondre aux demandes d'assistance",
    s3e: "Pour améliorer le service",
    s4h: "4. Services tiers",
    s4p: "Nous partageons des données avec les services de confiance suivants :",
    s4a: "Supabase — base de données et authentification (région UE)",
    s4b: "OpenAI — interprétation IA (votre texte est envoyé à OpenAI pour traitement)",
    s4c: "Stripe — traitement des paiements",
    s4end: "Nous ne vendons pas vos données à des tiers.",
    s5h: "5. Conservation des données",
    s5: "Vos données sont conservées tant que votre compte est actif. Vous pouvez supprimer votre compte et toutes les données associées à tout moment depuis les Paramètres. Après suppression, vos données sont définitivement effacées sous 30 jours.",
    s6h: "6. Cookies",
    s6: "Nous utilisons uniquement les cookies essentiels pour l'authentification et la session. Nous n'utilisons pas de cookies de suivi ou publicitaires.",
    s7h: "7. Vos droits (RGPD)",
    s7p: "En tant que résident de l'UE, vous avez le droit de :",
    s7a: "Accéder aux données personnelles que nous détenons sur vous",
    s7b: "Demander la correction de données inexactes",
    s7c: "Demander la suppression de vos données (\"droit à l'oubli\")",
    s7d: "Vous opposer au traitement de vos données",
    s7e: "Portabilité des données",
    s7end: "Contactez-nous via le formulaire d'assistance dans les Paramètres ou par e-mail : noctiraeai@gmail.com.",
    s8h: "8. Sécurité",
    s8: "Nous prenons des mesures techniques raisonnables pour protéger vos données, notamment des connexions chiffrées (HTTPS). Aucune transmission sur Internet n'est cependant sécurisée à 100%.",
    s9h: "9. Modifications de cette politique",
    s9: "Nous pouvons mettre à jour cette politique. Nous vous informerons des changements importants par e-mail ou notification dans l'application.",
    s10h: "10. Contact",
    s10: "Des questions ? Contactez-nous : noctiraeai@gmail.com.",
  },
  es: {
    back: "Volver", title: "Política de privacidad", updated: "Última actualización: marzo 2025",
    s1h: "1. Quiénes somos",
    s1: "Noctirae es un servicio de diario de sueños e interpretación basado en IA. Al usar este servicio, aceptas la recopilación y uso de información según se describe en esta política.",
    s2h: "2. Qué recopilamos",
    s2a: "Información de cuenta — tu dirección de correo electrónico al registrarte",
    s2b: "Contenido de sueños — las descripciones de sueños que envías para interpretación",
    s2c: "Datos de uso — páginas visitadas, funciones usadas, duración de sesión",
    s2d: "Datos de pago — procesados por Stripe; nunca almacenamos los datos de tu tarjeta",
    s3h: "3. Cómo usamos tus datos",
    s3a: "Para proporcionar interpretaciones de sueños mediante IA (OpenAI)",
    s3b: "Para guardar tu diario de sueños y mostrar patrones",
    s3c: "Para gestionar tu suscripción (Stripe)",
    s3d: "Para responder solicitudes de soporte",
    s3e: "Para mejorar el servicio",
    s4h: "4. Servicios de terceros",
    s4p: "Compartimos datos con los siguientes servicios de confianza:",
    s4a: "Supabase — base de datos y autenticación (región UE)",
    s4b: "OpenAI — interpretación IA (tu texto se envía a OpenAI para procesamiento)",
    s4c: "Stripe — procesamiento de pagos",
    s4end: "No vendemos tus datos a terceros.",
    s5h: "5. Retención de datos",
    s5: "Tus datos se conservan mientras tu cuenta esté activa. Puedes eliminar tu cuenta y todos los datos asociados en cualquier momento desde Configuración. Tras la eliminación, tus datos se borran definitivamente en 30 días.",
    s6h: "6. Cookies",
    s6: "Usamos solo las cookies esenciales para autenticación y sesión. No usamos cookies de seguimiento ni publicitarias.",
    s7h: "7. Tus derechos (RGPD)",
    s7p: "Como residente de la UE, tienes derecho a:",
    s7a: "Acceder a los datos personales que tenemos sobre ti",
    s7b: "Solicitar la corrección de datos inexactos",
    s7c: "Solicitar la eliminación de tus datos (\"derecho al olvido\")",
    s7d: "Oponerte al procesamiento de tus datos",
    s7e: "Portabilidad de datos",
    s7end: "Contacta con nosotros a través del formulario de soporte en Configuración o por correo: noctiraeai@gmail.com.",
    s8h: "8. Seguridad",
    s8: "Tomamos medidas técnicas razonables para proteger tus datos, incluyendo conexiones cifradas (HTTPS). Ninguna transmisión por Internet es 100% segura.",
    s9h: "9. Cambios en esta política",
    s9: "Podemos actualizar esta política. Te notificaremos sobre cambios importantes por correo o notificación en la app.",
    s10h: "10. Contacto",
    s10: "¿Preguntas? Escríbenos: noctiraeai@gmail.com.",
  },
  pt: {
    back: "Voltar", title: "Política de privacidade", updated: "Última atualização: março de 2025",
    s1h: "1. Quem somos",
    s1: "Noctirae é um serviço de diário de sonhos e interpretação baseado em IA. Ao usar este serviço, você concorda com a coleta e uso de informações conforme descrito nesta política.",
    s2h: "2. O que coletamos",
    s2a: "Informações de conta — seu endereço de e-mail ao se registrar",
    s2b: "Conteúdo de sonhos — as descrições de sonhos que você envia para interpretação",
    s2c: "Dados de uso — páginas visitadas, recursos usados, duração da sessão",
    s2d: "Dados de pagamento — processados pela Stripe; nunca armazenamos seus dados de cartão",
    s3h: "3. Como usamos seus dados",
    s3a: "Para fornecer interpretações de sonhos via IA (OpenAI)",
    s3b: "Para salvar seu diário de sonhos e mostrar padrões",
    s3c: "Para gerenciar sua assinatura (Stripe)",
    s3d: "Para responder a solicitações de suporte",
    s3e: "Para melhorar o serviço",
    s4h: "4. Serviços de terceiros",
    s4p: "Compartilhamos dados com os seguintes serviços confiáveis:",
    s4a: "Supabase — banco de dados e autenticação (região UE)",
    s4b: "OpenAI — interpretação por IA (seu texto é enviado à OpenAI para processamento)",
    s4c: "Stripe — processamento de pagamentos",
    s4end: "Não vendemos seus dados a terceiros.",
    s5h: "5. Retenção de dados",
    s5: "Seus dados são retidos enquanto sua conta estiver ativa. Você pode excluir sua conta e todos os dados associados a qualquer momento nas Configurações. Após a exclusão, seus dados são removidos permanentemente em 30 dias.",
    s6h: "6. Cookies",
    s6: "Usamos apenas cookies essenciais para autenticação e sessão. Não usamos cookies de rastreamento ou publicitários.",
    s7h: "7. Seus direitos (RGPD)",
    s7p: "Como residente da UE, você tem o direito de:",
    s7a: "Acessar os dados pessoais que temos sobre você",
    s7b: "Solicitar a correção de dados imprecisos",
    s7c: "Solicitar a exclusão dos seus dados (\"direito ao esquecimento\")",
    s7d: "Opor-se ao processamento dos seus dados",
    s7e: "Portabilidade de dados",
    s7end: "Entre em contato via formulário de suporte nas Configurações ou por e-mail: noctiraeai@gmail.com.",
    s8h: "8. Segurança",
    s8: "Tomamos medidas técnicas razoáveis para proteger seus dados, incluindo conexões criptografadas (HTTPS). Nenhuma transmissão pela Internet é 100% segura.",
    s9h: "9. Alterações nesta política",
    s9: "Podemos atualizar esta política. Notificaremos sobre mudanças importantes por e-mail ou notificação no aplicativo.",
    s10h: "10. Contato",
    s10: "Dúvidas? Entre em contato: noctiraeai@gmail.com.",
  },
  it: {
    back: "Indietro", title: "Informativa sulla privacy", updated: "Ultimo aggiornamento: marzo 2025",
    s1h: "1. Chi siamo",
    s1: "Noctirae è un servizio di diario dei sogni e interpretazione basato su IA. Utilizzando questo servizio, accetti la raccolta e l'uso delle informazioni come descritto in questa informativa.",
    s2h: "2. Cosa raccogliamo",
    s2a: "Informazioni sull'account — il tuo indirizzo e-mail alla registrazione",
    s2b: "Contenuto dei sogni — le descrizioni dei sogni che invii per l'interpretazione",
    s2c: "Dati di utilizzo — pagine visitate, funzionalità usate, durata della sessione",
    s2d: "Dati di pagamento — elaborati da Stripe; non memorizziamo mai i dati della tua carta",
    s3h: "3. Come utilizziamo i tuoi dati",
    s3a: "Per fornire interpretazioni dei sogni tramite IA (OpenAI)",
    s3b: "Per salvare il tuo diario dei sogni e mostrare i pattern nel tempo",
    s3c: "Per gestire il tuo abbonamento (Stripe)",
    s3d: "Per rispondere alle richieste di supporto",
    s3e: "Per migliorare il servizio",
    s4h: "4. Servizi di terze parti",
    s4p: "Condividiamo i dati con i seguenti servizi affidabili:",
    s4a: "Supabase — database e autenticazione (regione UE)",
    s4b: "OpenAI — interpretazione IA (il tuo testo viene inviato a OpenAI per l'elaborazione)",
    s4c: "Stripe — elaborazione dei pagamenti",
    s4end: "Non vendiamo i tuoi dati a terzi.",
    s5h: "5. Conservazione dei dati",
    s5: "I tuoi dati vengono conservati finché il tuo account è attivo. Puoi eliminare il tuo account e tutti i dati associati in qualsiasi momento dalle Impostazioni. Dopo l'eliminazione, i tuoi dati vengono rimossi definitivamente entro 30 giorni.",
    s6h: "6. Cookie",
    s6: "Utilizziamo solo i cookie essenziali per l'autenticazione e la sessione. Non utilizziamo cookie di tracciamento o pubblicitari.",
    s7h: "7. I tuoi diritti (GDPR)",
    s7p: "Come residente dell'UE, hai il diritto di:",
    s7a: "Accedere ai dati personali che deteniamo su di te",
    s7b: "Richiedere la correzione di dati inesatti",
    s7c: "Richiedere la cancellazione dei tuoi dati (\"diritto all'oblio\")",
    s7d: "Opporti al trattamento dei tuoi dati",
    s7e: "Portabilità dei dati",
    s7end: "Per esercitare questi diritti, contattaci tramite il modulo di supporto nelle Impostazioni o via e-mail: noctiraeai@gmail.com.",
    s8h: "8. Sicurezza",
    s8: "Adottiamo misure tecniche adeguate per proteggere i tuoi dati, incluse connessioni crittografate (HTTPS). Nessuna trasmissione su Internet è però sicura al 100%.",
    s9h: "9. Modifiche a questa informativa",
    s9: "Potremmo aggiornare questa informativa. Ti informeremo delle modifiche significative tramite e-mail o notifica nell'app.",
    s10h: "10. Contatti",
    s10: "Domande? Scrivici: noctiraeai@gmail.com.",
  },
  pl: {
    back: "Wróć", title: "Polityka prywatności", updated: "Ostatnia aktualizacja: marzec 2025",
    s1h: "1. Kim jesteśmy",
    s1: "Noctirae to usługa dziennika snów i interpretacji oparta na AI. Korzystając z tej usługi, wyrażasz zgodę na gromadzenie i wykorzystywanie informacji opisanych w tej polityce.",
    s2h: "2. Co zbieramy",
    s2a: "Informacje o koncie — Twój adres e-mail podczas rejestracji",
    s2b: "Treść snów — opisy snów przesyłane do interpretacji",
    s2c: "Dane użytkowania — odwiedzone strony, używane funkcje, czas sesji",
    s2d: "Dane płatnicze — przetwarzane przez Stripe; nigdy nie przechowujemy danych karty",
    s3h: "3. Jak wykorzystujemy Twoje dane",
    s3a: "Do dostarczania interpretacji snów przez AI (OpenAI)",
    s3b: "Do zapisywania dziennika snów i pokazywania wzorców w czasie",
    s3c: "Do zarządzania subskrypcją (Stripe)",
    s3d: "Do odpowiadania na prośby o pomoc",
    s3e: "Do ulepszania usługi",
    s4h: "4. Usługi zewnętrzne",
    s4p: "Udostępniamy dane następującym zaufanym usługom:",
    s4a: "Supabase — baza danych i uwierzytelnianie (region UE)",
    s4b: "OpenAI — interpretacja AI (Twój tekst jest wysyłany do OpenAI)",
    s4c: "Stripe — przetwarzanie płatności",
    s4end: "Nie sprzedajemy Twoich danych żadnym stronom trzecim.",
    s5h: "5. Przechowywanie danych",
    s5: "Twoje dane są przechowywane tak długo, jak Twoje konto jest aktywne. Możesz usunąć konto i wszystkie powiązane dane w dowolnym momencie z poziomu Ustawień. Po usunięciu dane są trwale usuwane w ciągu 30 dni.",
    s6h: "6. Pliki cookie",
    s6: "Używamy wyłącznie niezbędnych plików cookie do uwierzytelniania i sesji. Nie używamy plików cookie śledzących ani reklamowych.",
    s7h: "7. Twoje prawa (RODO)",
    s7p: "Jako mieszkaniec UE masz prawo do:",
    s7a: "Dostępu do swoich danych osobowych",
    s7b: "Sprostowania nieprawidłowych danych",
    s7c: "Usunięcia danych (\"prawo do bycia zapomnianym\")",
    s7d: "Sprzeciwu wobec przetwarzania danych",
    s7e: "Przenoszenia danych",
    s7end: "Skontaktuj się z nami przez formularz pomocy w Ustawieniach lub e-mailem: noctiraeai@gmail.com.",
    s8h: "8. Bezpieczeństwo",
    s8: "Stosujemy odpowiednie środki techniczne w celu ochrony danych, w tym szyfrowane połączenia (HTTPS). Żadna transmisja internetowa nie jest jednak w 100% bezpieczna.",
    s9h: "9. Zmiany w polityce",
    s9: "Możemy aktualizować tę politykę. O istotnych zmianach poinformujemy e-mailem lub powiadomieniem w aplikacji.",
    s10h: "10. Kontakt",
    s10: "Pytania? Napisz do nas: noctiraeai@gmail.com.",
  },
  ru: {
    back: "Назад", title: "Политика конфиденциальности", updated: "Последнее обновление: март 2025",
    s1h: "1. Кто мы",
    s1: "Noctirae — сервис для ведения дневника снов и их интерпретации на основе ИИ. Используя этот сервис, вы соглашаетесь со сбором и использованием информации, описанной в этой политике.",
    s2h: "2. Что мы собираем",
    s2a: "Данные аккаунта — ваш адрес электронной почты при регистрации",
    s2b: "Содержание снов — описания снов, которые вы отправляете на интерпретацию",
    s2c: "Данные об использовании — посещённые страницы, использованные функции, длительность сессии",
    s2d: "Платёжные данные — обрабатываются Stripe; мы никогда не храним данные вашей карты",
    s3h: "3. Как мы используем ваши данные",
    s3a: "Для предоставления интерпретаций снов через ИИ (OpenAI)",
    s3b: "Для сохранения вашего дневника снов и отображения паттернов",
    s3c: "Для управления вашей подпиской (Stripe)",
    s3d: "Для ответов на запросы поддержки",
    s3e: "Для улучшения сервиса",
    s4h: "4. Сторонние сервисы",
    s4p: "Мы передаём данные следующим доверенным сервисам:",
    s4a: "Supabase — база данных и аутентификация (регион ЕС)",
    s4b: "OpenAI — ИИ-интерпретация (ваш текст отправляется в OpenAI для обработки)",
    s4c: "Stripe — обработка платежей",
    s4end: "Мы не продаём ваши данные третьим лицам.",
    s5h: "5. Хранение данных",
    s5: "Ваши данные хранятся, пока ваш аккаунт активен. Вы можете удалить аккаунт и все связанные данные в любой момент в Настройках. После удаления данные будут окончательно удалены в течение 30 дней.",
    s6h: "6. Файлы cookie",
    s6: "Мы используем только необходимые файлы cookie для аутентификации и сессии. Мы не используем отслеживающие или рекламные cookie.",
    s7h: "7. Ваши права (GDPR)",
    s7p: "Как резидент ЕС, вы имеете право на:",
    s7a: "Доступ к хранимым персональным данным",
    s7b: "Исправление неточных данных",
    s7c: "Удаление данных («право на забвение»)",
    s7d: "Возражение против обработки данных",
    s7e: "Перенос данных",
    s7end: "Для реализации этих прав свяжитесь с нами через форму поддержки в Настройках или по e-mail: noctiraeai@gmail.com.",
    s8h: "8. Безопасность",
    s8: "Мы принимаем разумные технические меры для защиты данных, включая зашифрованные соединения (HTTPS). Однако ни одна интернет-передача не является 100% безопасной.",
    s9h: "9. Изменения политики",
    s9: "Мы можем обновлять эту политику. О существенных изменениях уведомим по e-mail или в приложении.",
    s10h: "10. Контакты",
    s10: "Вопросы? Напишите нам: noctiraeai@gmail.com.",
  },
  uk: {
    back: "Назад", title: "Політика конфіденційності", updated: "Останнє оновлення: березень 2025",
    s1h: "1. Хто ми",
    s1: "Noctirae — сервіс для ведення щоденника снів та їх інтерпретації на основі ШІ. Використовуючи цей сервіс, ви погоджуєтесь зі збором та використанням інформації, описаної в цій політиці.",
    s2h: "2. Що ми збираємо",
    s2a: "Дані облікового запису — ваша електронна адреса при реєстрації",
    s2b: "Вміст снів — описи снів, які ви надсилаєте на інтерпретацію",
    s2c: "Дані використання — відвідані сторінки, використані функції, тривалість сесії",
    s2d: "Платіжні дані — обробляються Stripe; ми ніколи не зберігаємо дані вашої картки",
    s3h: "3. Як ми використовуємо ваші дані",
    s3a: "Для надання інтерпретацій снів через ШІ (OpenAI)",
    s3b: "Для збереження щоденника снів та відображення закономірностей",
    s3c: "Для управління вашою підпискою (Stripe)",
    s3d: "Для відповідей на запити підтримки",
    s3e: "Для покращення сервісу",
    s4h: "4. Сторонні сервіси",
    s4p: "Ми передаємо дані наступним довіреним сервісам:",
    s4a: "Supabase — база даних та автентифікація (регіон ЄС)",
    s4b: "OpenAI — ШІ-інтерпретація (ваш текст надсилається в OpenAI для обробки)",
    s4c: "Stripe — обробка платежів",
    s4end: "Ми не продаємо ваші дані третім особам.",
    s5h: "5. Зберігання даних",
    s5: "Ваші дані зберігаються, поки ваш обліковий запис активний. Ви можете видалити обліковий запис і всі пов'язані дані будь-коли в Налаштуваннях. Після видалення дані буде остаточно видалено протягом 30 днів.",
    s6h: "6. Файли cookie",
    s6: "Ми використовуємо лише необхідні файли cookie для автентифікації та сесії. Ми не використовуємо відстежуючі чи рекламні cookie.",
    s7h: "7. Ваші права (GDPR)",
    s7p: "Як резидент ЄС, ви маєте право на:",
    s7a: "Доступ до особистих даних, які ми зберігаємо",
    s7b: "Виправлення неточних даних",
    s7c: "Видалення даних («право на забуття»)",
    s7d: "Заперечення проти обробки даних",
    s7e: "Перенесення даних",
    s7end: "Для реалізації цих прав зв'яжіться з нами через форму підтримки в Налаштуваннях або e-mail: noctiraeai@gmail.com.",
    s8h: "8. Безпека",
    s8: "Ми вживаємо розумних технічних заходів для захисту даних, включаючи зашифровані з'єднання (HTTPS). Однак жодна інтернет-передача не є на 100% безпечною.",
    s9h: "9. Зміни в політиці",
    s9: "Ми можемо оновлювати цю політику. Про суттєві зміни повідомимо електронною поштою або в застосунку.",
    s10h: "10. Контакти",
    s10: "Запитання? Напишіть нам: noctiraeai@gmail.com.",
  },
  zh: {
    back: "返回", title: "隐私政策", updated: "最后更新：2025年3月",
    s1h: "1. 关于我们",
    s1: "Noctirae 是一款基于AI的梦境日记与解析服务。使用本服务即表示您同意按本政策所述收集和使用信息。",
    s2h: "2. 我们收集的信息",
    s2a: "账户信息 — 注册时的电子邮件地址",
    s2b: "梦境内容 — 您提交解析的梦境描述",
    s2c: "使用数据 — 访问页面、使用功能、会话时长",
    s2d: "支付数据 — 由Stripe处理；我们从不存储您的银行卡信息",
    s3h: "3. 我们如何使用您的数据",
    s3a: "通过AI（OpenAI）提供梦境解析",
    s3b: "保存您的梦境日记并展示规律",
    s3c: "管理您的订阅（Stripe）",
    s3d: "回复支持请求",
    s3e: "改进服务",
    s4h: "4. 第三方服务",
    s4p: "我们与以下可信服务共享数据以运营产品：",
    s4a: "Supabase — 数据库与身份验证（欧盟地区）",
    s4b: "OpenAI — AI解析（您的梦境文本将发送至OpenAI处理）",
    s4c: "Stripe — 支付处理",
    s4end: "我们不会将您的数据出售给任何第三方。",
    s5h: "5. 数据保留",
    s5: "您的数据在账户活跃期间保留。您可随时在设置页面删除账户及所有相关数据。删除后，您的数据将在30天内被永久移除。",
    s6h: "6. Cookie",
    s6: "我们仅使用身份验证和会话维护所必需的Cookie，不使用跟踪或广告Cookie。",
    s7h: "7. 您的权利（GDPR）",
    s7p: "作为欧盟居民，您有权：",
    s7a: "访问我们持有的您的个人数据",
    s7b: "请求更正不准确的数据",
    s7c: "请求删除您的数据（\"被遗忘权\"）",
    s7d: "反对处理您的数据",
    s7e: "数据可携带性",
    s7end: "如需行使上述权利，请通过设置中的帮助与支持表单联系我们，或发送邮件至：noctiraeai@gmail.com。",
    s8h: "8. 安全性",
    s8: "我们采取合理的技术措施保护您的数据，包括加密连接（HTTPS）和安全数据库存储。但任何互联网传输都无法做到100%安全。",
    s9h: "9. 政策变更",
    s9: "我们可能会不时更新本政策。重大变更将通过电子邮件或应用内通知告知您。",
    s10h: "10. 联系我们",
    s10: "有疑问？请联系我们：noctiraeai@gmail.com。",
  },
  ja: {
    back: "戻る", title: "プライバシーポリシー", updated: "最終更新：2025年3月",
    s1h: "1. 私たちについて",
    s1: "NoctiræはAIを活用した夢の日記と解釈サービスです。本サービスを利用することで、このポリシーに記載された情報の収集および使用に同意したものとみなされます。",
    s2h: "2. 収集する情報",
    s2a: "アカウント情報 — 登録時のメールアドレス",
    s2b: "夢のコンテンツ — 解釈のために送信した夢の説明",
    s2c: "利用データ — 訪問したページ、使用した機能、セッション時間",
    s2d: "支払いデータ — Stripeが処理します。カード情報は保存しません",
    s3h: "3. データの使用方法",
    s3a: "AI（OpenAI）による夢の解釈を提供するため",
    s3b: "夢の日記を保存し、パターンを表示するため",
    s3c: "サブスクリプションを管理するため（Stripe）",
    s3d: "サポートリクエストに対応するため",
    s3e: "サービスを改善するため",
    s4h: "4. 第三者サービス",
    s4p: "製品運営のため、以下の信頼できるサービスとデータを共有します：",
    s4a: "Supabase — データベースと認証（EUリージョン）",
    s4b: "OpenAI — AI解釈（夢のテキストが処理のためOpenAIに送信されます）",
    s4c: "Stripe — 決済処理",
    s4end: "第三者にデータを販売することはありません。",
    s5h: "5. データの保持",
    s5: "データはアカウントが有効な間保持されます。設定ページからいつでもアカウントと関連データを削除できます。削除後、データは30日以内に完全に削除されます。",
    s6h: "6. Cookie",
    s6: "認証とセッション維持に必要な必須Cookieのみ使用します。トラッキングや広告目的のCookieは使用しません。",
    s7h: "7. お客様の権利（GDPR）",
    s7p: "EU居住者として、以下の権利があります：",
    s7a: "当社が保有する個人データへのアクセス",
    s7b: "不正確なデータの訂正請求",
    s7c: "データの削除請求（「忘れられる権利」）",
    s7d: "データ処理への異議申し立て",
    s7e: "データポータビリティ",
    s7end: "これらの権利を行使するには、設定のヘルプ＆サポートフォームからご連絡いただくか、noctiraeai@gmail.comにメールでご連絡ください。",
    s8h: "8. セキュリティ",
    s8: "暗号化接続（HTTPS）や安全なデータベース保存など、合理的な技術的措置を講じてデータを保護しています。ただし、インターネット上の通信が100%安全であることは保証できません。",
    s9h: "9. ポリシーの変更",
    s9: "本ポリシーを随時更新する場合があります。重要な変更はメールまたはアプリ内通知でお知らせします。",
    s10h: "10. お問い合わせ",
    s10: "ご質問はこちら：noctiraeai@gmail.com",
  },
};

export default function PrivacyPage() {
  const locale = useLocale();
  const t = content[locale] ?? content.en;

  return (
    <div className="min-h-screen px-4 py-10 max-w-2xl mx-auto">
      <a
        href="/settings"
        className="inline-flex items-center gap-2 text-dream-500 hover:text-dream-300 text-sm mb-8 transition-colors"
      >
        <ArrowLeft size={16} /> {t.back}
      </a>

      <h1 className="text-2xl font-bold text-dream-100 mb-2">{t.title}</h1>
      <p className="text-dream-500 text-sm mb-8">{t.updated}</p>

      <div className="space-y-8 text-dream-300 text-sm leading-relaxed">
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s1h}</h2>
          <p>{t.s1}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s2h}</h2>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s2a, t.s2b, t.s2c, t.s2d].map((item) => <li key={item}>{item}</li>)}
          </ul>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s3h}</h2>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s3a, t.s3b, t.s3c, t.s3d, t.s3e].map((item) => <li key={item}>{item}</li>)}
          </ul>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s4h}</h2>
          <p className="mb-3">{t.s4p}</p>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s4a, t.s4b, t.s4c].map((item) => <li key={item}>{item}</li>)}
          </ul>
          <p className="mt-3">{t.s4end}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s5h}</h2>
          <p>{t.s5}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s6h}</h2>
          <p>{t.s6}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s7h}</h2>
          <p className="mb-3">{t.s7p}</p>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s7a, t.s7b, t.s7c, t.s7d, t.s7e].map((item) => <li key={item}>{item}</li>)}
          </ul>
          <p className="mt-3">{t.s7end}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s8h}</h2>
          <p>{t.s8}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s9h}</h2>
          <p>{t.s9}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s10h}</h2>
          <p>
            {t.s10.replace("noctiraeai@gmail.com", "")}{" "}
            <a href="mailto:noctiraeai@gmail.com" className="text-dream-400 hover:text-dream-200 underline">
              noctiraeai@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
