"use client";

import { ArrowLeft } from "lucide-react";
import { useLocale } from "@/components/layout/LocaleProvider";

const content: Record<string, {
  back: string; title: string; updated: string;
  s1h: string; s1: string;
  s2h: string; s2: string;
  s3h: string; s3: string;
  s4h: string; s4a: string; s4b: string; s4c: string; s4d: string;
  s5h: string; s5p: string; s5a: string; s5b: string; s5c: string; s5d: string;
  s6h: string; s6a: string; s6b: string; s6c: string; s6d: string;
  s7h: string; s7: string;
  s8h: string; s8: string;
  s9h: string; s9: string;
  s10h: string; s10: string;
  s11h: string; s11: string;
}> = {
  en: {
    back: "Back", title: "Terms of Service", updated: "Last updated: March 2025",
    s1h: "1. Acceptance of Terms",
    s1: "By accessing or using Noctirae, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.",
    s2h: "2. Description of Service",
    s2: "Noctirae is an AI-powered tool that provides dream interpretations for entertainment and personal reflection purposes. The service offers free and premium subscription tiers.",
    s3h: "3. Important Disclaimer",
    s3: "Dream interpretations provided by this service are generated by artificial intelligence and are intended for entertainment and personal reflection only. They do not constitute medical, psychological, psychiatric, or therapeutic advice. If you are experiencing mental health concerns, please consult a qualified healthcare professional.",
    s4h: "4. User Accounts",
    s4a: "You must be at least 16 years old to create an account",
    s4b: "You are responsible for maintaining the security of your account",
    s4c: "You must provide accurate information when registering",
    s4d: "One account per person",
    s5h: "5. Acceptable Use",
    s5p: "You agree not to:",
    s5a: "Submit content that is illegal, harmful, or offensive",
    s5b: "Attempt to reverse-engineer or abuse the AI system",
    s5c: "Share your account with others",
    s5d: "Use the service for any automated or commercial scraping",
    s6h: "6. Subscription & Payments",
    s6a: "Premium subscriptions are billed monthly via Stripe",
    s6b: "You may cancel your subscription at any time from Settings",
    s6c: "Cancellation takes effect at the end of the current billing period",
    s6d: "Refunds are not provided for partial billing periods",
    s7h: "7. Your Content",
    s7: "You retain ownership of the dream content you submit. By submitting content, you grant us a limited licence to process it for the purpose of providing the service (including sending it to OpenAI for interpretation). We do not use your dream content to train AI models.",
    s8h: "8. Limitation of Liability",
    s8: "Noctirae is provided \"as is\". We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount you paid us in the last 12 months.",
    s9h: "9. Termination",
    s9: "We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time from the Settings page.",
    s10h: "10. Governing Law",
    s10: "These terms are governed by the laws of the Republic of Lithuania and applicable EU regulations.",
    s11h: "11. Contact",
    s11: "Questions about these terms? Contact us at noctiraeai@gmail.com.",
  },
  lt: {
    back: "Grįžti", title: "Paslaugų teikimo sąlygos", updated: "Paskutinį kartą atnaujinta: 2025 m. kovas",
    s1h: "1. Sąlygų priėmimas",
    s1: "Prisijungdami prie Noctirae arba naudodamiesi ja, jūs sutinkate su šiomis paslaugų teikimo sąlygomis. Jei nesutinkate, prašome nesinaudoti paslauga.",
    s2h: "2. Paslaugos aprašymas",
    s2: "Noctirae yra AI pagrindu veikianti priemonė, teikianti sapnų interpretacijas pramogų ir asmeninių apmąstymų tikslais. Paslauga siūlo nemokamą ir premium prenumeratos lygius.",
    s3h: "3. Svarbus atsakomybės atsisakymas",
    s3: "Šios paslaugos teikiamos sapnų interpretacijos yra generuojamos dirbtinio intelekto ir skirtos tik pramogoms ir asmeniniams apmąstymams. Jos nėra medicinos, psichologinės, psichiatrinės ar terapinės konsultacijos. Jei jaučiate su psichine sveikata susijusių problemų, kreipkitės į kvalifikuotą sveikatos priežiūros specialistą.",
    s4h: "4. Naudotojų paskyros",
    s4a: "Jums turi būti bent 16 metų, kad galėtumėte sukurti paskyrą",
    s4b: "Jūs esate atsakingi už savo paskyros saugumo palaikymą",
    s4c: "Registruojantis turite pateikti tikslią informaciją",
    s4d: "Viena paskyra vienam asmeniui",
    s5h: "5. Priimtinas naudojimas",
    s5p: "Jūs sutinkate:",
    s5a: "Nepateikti neteisėto, žalingo ar įžeidžiančio turinio",
    s5b: "Nebandyti pakeisti ar piktnaudžiauti AI sistema",
    s5c: "Nesidalinti paskyra su kitais",
    s5d: "Nenaudoti paslaugos automatizuotam ar komerciniam duomenų rinkimui",
    s6h: "6. Prenumerata ir mokėjimai",
    s6a: "Premium prenumerata apmokestinama kas mėnesį per Stripe",
    s6b: "Prenumeratą galite atšaukti bet kada iš Nustatymų",
    s6c: "Atšaukimas įsigalioja pasibaigus dabartiniam atsiskaitymo laikotarpiui",
    s6d: "Dalinių atsiskaitymo laikotarpių kompensacijos neteikiamos",
    s7h: "7. Jūsų turinys",
    s7: "Jūs išlaikote nuosavybės teisę į pateiktą sapnų turinį. Pateikdami turinį, jūs suteikiate mums ribotą licenciją jį apdoroti paslaugos teikimo tikslu (įskaitant siuntimą OpenAI interpretacijai). Mes nenaudojame jūsų sapnų turinio AI modeliams apmokyti.",
    s8h: "8. Atsakomybės apribojimas",
    s8: "Noctirae teikiama \"tokia, kokia yra\". Mes nesame atsakingi už jokią netiesioginę, atsitiktinę ar pasekminę žalą, atsiradusią dėl paslaugos naudojimo. Mūsų bendra atsakomybė neviršys sumos, kurią jūs sumokėjote per paskutinius 12 mėnesių.",
    s9h: "9. Nutraukimas",
    s9: "Mes pasiliekame teisę sustabdyti arba nutraukti paskyras, pažeidžiančias šias sąlygas. Galite ištrinti paskyrą bet kada iš Nustatymų puslapio.",
    s10h: "10. Taikoma teisė",
    s10: "Šioms sąlygoms taikomi Lietuvos Respublikos įstatymai ir taikomi ES reglamentai.",
    s11h: "11. Kontaktai",
    s11: "Turite klausimų dėl šių sąlygų? Susisiekite su mumis: noctiraeai@gmail.com.",
  },
  de: {
    back: "Zurück", title: "Nutzungsbedingungen", updated: "Zuletzt aktualisiert: März 2025",
    s1h: "1. Annahme der Bedingungen",
    s1: "Durch den Zugriff auf oder die Nutzung von Noctirae stimmen Sie diesen Nutzungsbedingungen zu. Wenn Sie nicht einverstanden sind, nutzen Sie den Dienst bitte nicht.",
    s2h: "2. Beschreibung des Dienstes",
    s2: "Noctirae ist ein KI-gestütztes Tool für Traumdeutungen zur Unterhaltung und persönlichen Reflexion. Der Dienst bietet kostenlose und Premium-Abonnements.",
    s3h: "3. Wichtiger Haftungsausschluss",
    s3: "Die Traumdeutungen werden von KI generiert und dienen ausschließlich der Unterhaltung und persönlichen Reflexion. Sie stellen keine medizinische, psychologische oder therapeutische Beratung dar. Bei psychischen Problemen wenden Sie sich bitte an einen Fachmann.",
    s4h: "4. Benutzerkonten",
    s4a: "Sie müssen mindestens 16 Jahre alt sein",
    s4b: "Sie sind für die Sicherheit Ihres Kontos verantwortlich",
    s4c: "Sie müssen genaue Angaben bei der Registrierung machen",
    s4d: "Ein Konto pro Person",
    s5h: "5. Zulässige Nutzung",
    s5p: "Sie stimmen zu, Folgendes zu unterlassen:",
    s5a: "Einreichen illegaler, schädlicher oder anstößiger Inhalte",
    s5b: "Versuche, das KI-System zu dekompilieren oder zu missbrauchen",
    s5c: "Teilen des Kontos mit anderen",
    s5d: "Nutzung für automatisiertes oder kommerzielles Scraping",
    s6h: "6. Abonnement & Zahlungen",
    s6a: "Premium-Abonnements werden monatlich über Stripe abgerechnet",
    s6b: "Sie können jederzeit über die Einstellungen kündigen",
    s6c: "Die Kündigung gilt am Ende des Abrechnungszeitraums",
    s6d: "Keine Rückerstattungen für anteilige Zeiträume",
    s7h: "7. Ihre Inhalte",
    s7: "Sie behalten das Eigentum an Ihren Trauminhalten. Mit der Einreichung erteilen Sie uns eine begrenzte Lizenz zur Verarbeitung (einschließlich Übermittlung an OpenAI). Wir verwenden Inhalte nicht zum Training von KI-Modellen.",
    s8h: "8. Haftungsbeschränkung",
    s8: "Noctirae wird \u201ewie besehen\u201c bereitgestellt. Wir haften nicht für indirekte oder Folgeschäden. Unsere Gesamthaftung übersteigt nicht den in den letzten 12 Monaten gezahlten Betrag.",
    s9h: "9. Kündigung",
    s9: "Wir behalten uns das Recht vor, Konten bei Verstößen zu sperren. Sie können Ihr Konto jederzeit über die Einstellungen löschen.",
    s10h: "10. Geltendes Recht",
    s10: "Diese Bedingungen unterliegen dem Recht der Republik Litauen und EU-Vorschriften.",
    s11h: "11. Kontakt",
    s11: "Fragen? Schreiben Sie uns: noctiraeai@gmail.com.",
  },
  fr: {
    back: "Retour", title: "Conditions d'utilisation", updated: "Dernière mise à jour : mars 2025",
    s1h: "1. Acceptation des conditions",
    s1: "En accédant à Noctirae ou en l'utilisant, vous acceptez d'être lié par ces Conditions d'utilisation. Si vous n'êtes pas d'accord, veuillez ne pas utiliser le service.",
    s2h: "2. Description du service",
    s2: "Noctirae est un outil basé sur l'IA qui fournit des interprétations de rêves à des fins de divertissement et de réflexion personnelle. Le service propose des niveaux gratuits et premium.",
    s3h: "3. Avertissement important",
    s3: "Les interprétations de rêves sont générées par intelligence artificielle et sont destinées uniquement au divertissement et à la réflexion personnelle. Elles ne constituent pas un avis médical, psychologique ou thérapeutique. En cas de problèmes de santé mentale, consultez un professionnel.",
    s4h: "4. Comptes utilisateurs",
    s4a: "Vous devez avoir au moins 16 ans pour créer un compte",
    s4b: "Vous êtes responsable de la sécurité de votre compte",
    s4c: "Vous devez fournir des informations exactes lors de l'inscription",
    s4d: "Un compte par personne",
    s5h: "5. Utilisation acceptable",
    s5p: "Vous vous engagez à ne pas :",
    s5a: "Soumettre du contenu illégal, nuisible ou offensant",
    s5b: "Tenter de décompiler ou d'abuser du système IA",
    s5c: "Partager votre compte avec d'autres",
    s5d: "Utiliser le service pour du scraping automatisé ou commercial",
    s6h: "6. Abonnement & paiements",
    s6a: "Les abonnements premium sont facturés mensuellement via Stripe",
    s6b: "Vous pouvez annuler votre abonnement à tout moment dans les Paramètres",
    s6c: "L'annulation prend effet à la fin de la période de facturation en cours",
    s6d: "Aucun remboursement pour les périodes partielles",
    s7h: "7. Votre contenu",
    s7: "Vous conservez la propriété du contenu de vos rêves. En soumettant du contenu, vous nous accordez une licence limitée pour le traiter (y compris l'envoi à OpenAI). Nous n'utilisons pas votre contenu pour entraîner des modèles IA.",
    s8h: "8. Limitation de responsabilité",
    s8: "Noctirae est fourni \"tel quel\". Nous ne sommes pas responsables des dommages indirects ou consécutifs. Notre responsabilité totale ne dépassera pas le montant payé au cours des 12 derniers mois.",
    s9h: "9. Résiliation",
    s9: "Nous nous réservons le droit de suspendre ou de résilier les comptes qui enfreignent ces conditions. Vous pouvez supprimer votre compte à tout moment.",
    s10h: "10. Droit applicable",
    s10: "Ces conditions sont régies par les lois de la République de Lituanie et les réglementations UE applicables.",
    s11h: "11. Contact",
    s11: "Des questions ? Contactez-nous : noctiraeai@gmail.com.",
  },
  es: {
    back: "Volver", title: "Términos de servicio", updated: "Última actualización: marzo 2025",
    s1h: "1. Aceptación de los términos",
    s1: "Al acceder o usar Noctirae, aceptas estar sujeto a estos Términos de servicio. Si no estás de acuerdo, no uses el servicio.",
    s2h: "2. Descripción del servicio",
    s2: "Noctirae es una herramienta basada en IA que proporciona interpretaciones de sueños para entretenimiento y reflexión personal. El servicio ofrece niveles gratuitos y premium.",
    s3h: "3. Aviso importante",
    s3: "Las interpretaciones de sueños son generadas por inteligencia artificial y están destinadas únicamente al entretenimiento y la reflexión personal. No constituyen asesoramiento médico, psicológico o terapéutico. Si tienes problemas de salud mental, consulta a un profesional.",
    s4h: "4. Cuentas de usuario",
    s4a: "Debes tener al menos 16 años para crear una cuenta",
    s4b: "Eres responsable de mantener la seguridad de tu cuenta",
    s4c: "Debes proporcionar información precisa al registrarte",
    s4d: "Una cuenta por persona",
    s5h: "5. Uso aceptable",
    s5p: "Aceptas no:",
    s5a: "Enviar contenido ilegal, dañino u ofensivo",
    s5b: "Intentar hacer ingeniería inversa o abusar del sistema IA",
    s5c: "Compartir tu cuenta con otros",
    s5d: "Usar el servicio para scraping automatizado o comercial",
    s6h: "6. Suscripción y pagos",
    s6a: "Las suscripciones premium se facturan mensualmente a través de Stripe",
    s6b: "Puedes cancelar tu suscripción en cualquier momento desde Configuración",
    s6c: "La cancelación surte efecto al final del período de facturación actual",
    s6d: "No se realizan reembolsos por períodos parciales",
    s7h: "7. Tu contenido",
    s7: "Conservas la propiedad del contenido de tus sueños. Al enviarlo, nos otorgas una licencia limitada para procesarlo (incluyendo el envío a OpenAI). No usamos tu contenido para entrenar modelos de IA.",
    s8h: "8. Limitación de responsabilidad",
    s8: "Noctirae se proporciona \"tal cual\". No somos responsables de daños indirectos o consecuentes. Nuestra responsabilidad total no superará el importe pagado en los últimos 12 meses.",
    s9h: "9. Terminación",
    s9: "Nos reservamos el derecho de suspender o terminar cuentas que violen estos términos. Puedes eliminar tu cuenta en cualquier momento desde Configuración.",
    s10h: "10. Ley aplicable",
    s10: "Estos términos se rigen por las leyes de la República de Lituania y las regulaciones de la UE.",
    s11h: "11. Contacto",
    s11: "¿Preguntas? Escríbenos: noctiraeai@gmail.com.",
  },
  pt: {
    back: "Voltar", title: "Termos de serviço", updated: "Última atualização: março de 2025",
    s1h: "1. Aceitação dos termos",
    s1: "Ao acessar ou usar o Noctirae, você concorda em estar vinculado a estes Termos de serviço. Se não concordar, não use o serviço.",
    s2h: "2. Descrição do serviço",
    s2: "Noctirae é uma ferramenta baseada em IA que fornece interpretações de sonhos para entretenimento e reflexão pessoal. O serviço oferece níveis gratuitos e premium.",
    s3h: "3. Aviso importante",
    s3: "As interpretações de sonhos são geradas por inteligência artificial e destinam-se apenas ao entretenimento e reflexão pessoal. Não constituem aconselhamento médico, psicológico ou terapêutico. Em caso de problemas de saúde mental, consulte um profissional.",
    s4h: "4. Contas de usuário",
    s4a: "Você deve ter pelo menos 16 anos para criar uma conta",
    s4b: "Você é responsável por manter a segurança da sua conta",
    s4c: "Você deve fornecer informações precisas ao se registrar",
    s4d: "Uma conta por pessoa",
    s5h: "5. Uso aceitável",
    s5p: "Você concorda em não:",
    s5a: "Enviar conteúdo ilegal, prejudicial ou ofensivo",
    s5b: "Tentar fazer engenharia reversa ou abusar do sistema de IA",
    s5c: "Compartilhar sua conta com outras pessoas",
    s5d: "Usar o serviço para scraping automatizado ou comercial",
    s6h: "6. Assinatura e pagamentos",
    s6a: "As assinaturas premium são cobradas mensalmente via Stripe",
    s6b: "Você pode cancelar sua assinatura a qualquer momento nas Configurações",
    s6c: "O cancelamento entra em vigor no final do período de cobrança atual",
    s6d: "Reembolsos não são fornecidos para períodos parciais",
    s7h: "7. Seu conteúdo",
    s7: "Você retém a propriedade do conteúdo dos sonhos que envia. Ao enviá-lo, concede-nos uma licença limitada para processá-lo (incluindo o envio ao OpenAI). Não usamos seu conteúdo para treinar modelos de IA.",
    s8h: "8. Limitação de responsabilidade",
    s8: "Noctirae é fornecido \"como está\". Não somos responsáveis por danos indiretos ou consequentes. Nossa responsabilidade total não excederá o valor pago nos últimos 12 meses.",
    s9h: "9. Rescisão",
    s9: "Reservamo-nos o direito de suspender ou encerrar contas que violem estes termos. Você pode excluir sua conta a qualquer momento nas Configurações.",
    s10h: "10. Lei aplicável",
    s10: "Estes termos são regidos pelas leis da República da Lituânia e pelos regulamentos aplicáveis da UE.",
    s11h: "11. Contato",
    s11: "Dúvidas? Entre em contato: noctiraeai@gmail.com.",
  },
  it: {
    back: "Indietro", title: "Termini di servizio", updated: "Ultimo aggiornamento: marzo 2025",
    s1h: "1. Accettazione dei termini",
    s1: "Accedendo o utilizzando Noctirae, accetti di essere vincolato da questi Termini di servizio. Se non sei d'accordo, non utilizzare il servizio.",
    s2h: "2. Descrizione del servizio",
    s2: "Noctirae è uno strumento basato su IA che fornisce interpretazioni dei sogni per intrattenimento e riflessione personale. Il servizio offre livelli gratuiti e premium.",
    s3h: "3. Avvertenza importante",
    s3: "Le interpretazioni dei sogni sono generate dall'intelligenza artificiale e sono destinate esclusivamente all'intrattenimento e alla riflessione personale. Non costituiscono consulenza medica, psicologica o terapeutica. In caso di problemi di salute mentale, consultare un professionista.",
    s4h: "4. Account utente",
    s4a: "Devi avere almeno 16 anni per creare un account",
    s4b: "Sei responsabile della sicurezza del tuo account",
    s4c: "Devi fornire informazioni accurate durante la registrazione",
    s4d: "Un account per persona",
    s5h: "5. Uso accettabile",
    s5p: "Accetti di non:",
    s5a: "Inviare contenuti illegali, dannosi o offensivi",
    s5b: "Tentare di decompilare o abusare del sistema IA",
    s5c: "Condividere il tuo account con altri",
    s5d: "Utilizzare il servizio per scraping automatizzato o commerciale",
    s6h: "6. Abbonamento e pagamenti",
    s6a: "Gli abbonamenti premium vengono addebitati mensilmente tramite Stripe",
    s6b: "Puoi annullare l'abbonamento in qualsiasi momento dalle Impostazioni",
    s6c: "L'annullamento ha effetto alla fine del periodo di fatturazione corrente",
    s6d: "Non vengono forniti rimborsi per periodi parziali",
    s7h: "7. I tuoi contenuti",
    s7: "Mantieni la proprietà dei contenuti dei sogni che invii. Inviando contenuti, ci concedi una licenza limitata per elaborarli (incluso l'invio a OpenAI). Non utilizziamo i tuoi contenuti per addestrare modelli IA.",
    s8h: "8. Limitazione di responsabilità",
    s8: "Noctirae è fornito \"così com'è\". Non siamo responsabili per danni indiretti o consequenziali. La nostra responsabilità totale non supererà l'importo pagato negli ultimi 12 mesi.",
    s9h: "9. Risoluzione",
    s9: "Ci riserviamo il diritto di sospendere o chiudere account che violano questi termini. Puoi eliminare il tuo account in qualsiasi momento dalle Impostazioni.",
    s10h: "10. Legge applicabile",
    s10: "Questi termini sono regolati dalle leggi della Repubblica di Lituania e dai regolamenti UE applicabili.",
    s11h: "11. Contatti",
    s11: "Domande? Scrivici: noctiraeai@gmail.com.",
  },
  pl: {
    back: "Wróć", title: "Warunki korzystania z usługi", updated: "Ostatnia aktualizacja: marzec 2025",
    s1h: "1. Akceptacja warunków",
    s1: "Uzyskując dostęp do Noctirae lub korzystając z niego, zgadzasz się na te Warunki korzystania z usługi. Jeśli nie zgadzasz się, nie korzystaj z usługi.",
    s2h: "2. Opis usługi",
    s2: "Noctirae to narzędzie oparte na AI, które dostarcza interpretacje snów do celów rozrywkowych i osobistej refleksji. Usługa oferuje poziomy bezpłatny i premium.",
    s3h: "3. Ważne zastrzeżenie",
    s3: "Interpretacje snów są generowane przez sztuczną inteligencję i przeznaczone wyłącznie do rozrywki i osobistej refleksji. Nie stanowią porady medycznej, psychologicznej ani terapeutycznej. W przypadku problemów ze zdrowiem psychicznym skonsultuj się ze specjalistą.",
    s4h: "4. Konta użytkowników",
    s4a: "Musisz mieć co najmniej 16 lat, aby założyć konto",
    s4b: "Odpowiadasz za bezpieczeństwo swojego konta",
    s4c: "Musisz podać dokładne informacje podczas rejestracji",
    s4d: "Jedno konto na osobę",
    s5h: "5. Dopuszczalne użytkowanie",
    s5p: "Zgadzasz się nie:",
    s5a: "Przesyłać nielegalnych, szkodliwych lub obraźliwych treści",
    s5b: "Próbować odtwarzać lub nadużywać systemu AI",
    s5c: "Udostępniać konta innym",
    s5d: "Używać usługi do automatycznego lub komercyjnego scrapingu",
    s6h: "6. Subskrypcja i płatności",
    s6a: "Subskrypcje premium są rozliczane miesięcznie przez Stripe",
    s6b: "Możesz anulować subskrypcję w dowolnym momencie z Ustawień",
    s6c: "Anulowanie obowiązuje od końca bieżącego okresu rozliczeniowego",
    s6d: "Zwroty za częściowe okresy nie są zapewniane",
    s7h: "7. Twoje treści",
    s7: "Zachowujesz własność treści snów, które przesyłasz. Przesyłając treści, udzielasz nam ograniczonej licencji do ich przetwarzania (w tym wysyłania do OpenAI). Nie używamy treści do trenowania modeli AI.",
    s8h: "8. Ograniczenie odpowiedzialności",
    s8: "Noctirae jest dostarczane \"tak jak jest\". Nie ponosimy odpowiedzialności za pośrednie lub wtórne szkody. Nasza łączna odpowiedzialność nie przekroczy kwoty zapłaconej w ciągu ostatnich 12 miesięcy.",
    s9h: "9. Rozwiązanie umowy",
    s9: "Zastrzegamy sobie prawo do zawieszenia lub usunięcia kont naruszających te warunki. Możesz usunąć konto w dowolnym momencie z Ustawień.",
    s10h: "10. Prawo właściwe",
    s10: "Niniejsze warunki podlegają prawu Republiki Litewskiej i obowiązującym przepisom UE.",
    s11h: "11. Kontakt",
    s11: "Pytania? Napisz do nas: noctiraeai@gmail.com.",
  },
  ru: {
    back: "Назад", title: "Условия использования", updated: "Последнее обновление: март 2025",
    s1h: "1. Принятие условий",
    s1: "Получая доступ к Noctirae или используя его, вы соглашаетесь с настоящими Условиями использования. Если вы не согласны, не используйте сервис.",
    s2h: "2. Описание сервиса",
    s2: "Noctirae — инструмент на основе ИИ для интерпретации снов в развлекательных и личных целях. Сервис предлагает бесплатный и премиум-уровни.",
    s3h: "3. Важный отказ от ответственности",
    s3: "Интерпретации снов генерируются искусственным интеллектом и предназначены исключительно для развлечения и личного осмысления. Они не являются медицинской, психологической или терапевтической консультацией. При проблемах с психическим здоровьем обратитесь к специалисту.",
    s4h: "4. Учётные записи",
    s4a: "Вам должно быть не менее 16 лет для создания аккаунта",
    s4b: "Вы несёте ответственность за безопасность своего аккаунта",
    s4c: "При регистрации необходимо указывать точные данные",
    s4d: "Один аккаунт на одного человека",
    s5h: "5. Допустимое использование",
    s5p: "Вы соглашаетесь не:",
    s5a: "Публиковать незаконный, вредоносный или оскорбительный контент",
    s5b: "Пытаться декомпилировать или злоупотреблять системой ИИ",
    s5c: "Передавать аккаунт другим лицам",
    s5d: "Использовать сервис для автоматического или коммерческого сбора данных",
    s6h: "6. Подписка и оплата",
    s6a: "Премиум-подписки оплачиваются ежемесячно через Stripe",
    s6b: "Подписку можно отменить в любое время в Настройках",
    s6c: "Отмена вступает в силу в конце текущего платёжного периода",
    s6d: "Возврат средств за частичные периоды не предусмотрен",
    s7h: "7. Ваш контент",
    s7: "Вы сохраняете права на контент снов. Отправляя контент, вы предоставляете нам ограниченную лицензию на его обработку (включая отправку в OpenAI). Мы не используем контент для обучения ИИ-моделей.",
    s8h: "8. Ограничение ответственности",
    s8: "Noctirae предоставляется «как есть». Мы не несём ответственности за косвенный или случайный ущерб. Наша совокупная ответственность не превысит сумму, уплаченную за последние 12 месяцев.",
    s9h: "9. Прекращение",
    s9: "Мы оставляем за собой право приостановить или удалить аккаунты, нарушающие условия. Вы можете удалить аккаунт в любое время в Настройках.",
    s10h: "10. Применимое право",
    s10: "Настоящие условия регулируются законодательством Литовской Республики и применимыми нормами ЕС.",
    s11h: "11. Контакты",
    s11: "Вопросы? Напишите нам: noctiraeai@gmail.com.",
  },
  uk: {
    back: "Назад", title: "Умови використання", updated: "Останнє оновлення: березень 2025",
    s1h: "1. Прийняття умов",
    s1: "Отримуючи доступ до Noctirae або використовуючи його, ви погоджуєтесь з цими Умовами використання. Якщо ви не згодні, не використовуйте сервіс.",
    s2h: "2. Опис сервісу",
    s2: "Noctirae — інструмент на основі ШІ для інтерпретації снів у розважальних та особистих цілях. Сервіс пропонує безкоштовний і преміум-рівні.",
    s3h: "3. Важливе застереження",
    s3: "Інтерпретації снів генеруються штучним інтелектом і призначені виключно для розваги та особистого осмислення. Вони не є медичною, психологічною або терапевтичною консультацією. При проблемах з психічним здоров'ям зверніться до фахівця.",
    s4h: "4. Облікові записи",
    s4a: "Вам має бути не менше 16 років для створення облікового запису",
    s4b: "Ви несете відповідальність за безпеку свого облікового запису",
    s4c: "При реєстрації необхідно вказувати точні дані",
    s4d: "Один обліковий запис на одну особу",
    s5h: "5. Допустиме використання",
    s5p: "Ви погоджуєтесь не:",
    s5a: "Публікувати незаконний, шкідливий або образливий контент",
    s5b: "Намагатися декомпілювати або зловживати системою ШІ",
    s5c: "Передавати обліковий запис іншим особам",
    s5d: "Використовувати сервіс для автоматизованого або комерційного збору даних",
    s6h: "6. Підписка та оплата",
    s6a: "Преміум-підписки оплачуються щомісяця через Stripe",
    s6b: "Підписку можна скасувати будь-коли в Налаштуваннях",
    s6c: "Скасування набирає чинності в кінці поточного платіжного періоду",
    s6d: "Повернення коштів за часткові періоди не передбачено",
    s7h: "7. Ваш контент",
    s7: "Ви зберігаєте права на контент снів. Надсилаючи контент, ви надаєте нам обмежену ліцензію на його обробку (включаючи відправку до OpenAI). Ми не використовуємо контент для навчання ШІ-моделей.",
    s8h: "8. Обмеження відповідальності",
    s8: "Noctirae надається «як є». Ми не несемо відповідальності за непрямий або випадковий збиток. Наша сукупна відповідальність не перевищить суму, сплачену за останні 12 місяців.",
    s9h: "9. Припинення",
    s9: "Ми залишаємо за собою право призупинити або видалити облікові записи, що порушують умови. Ви можете видалити обліковий запис будь-коли в Налаштуваннях.",
    s10h: "10. Застосовне право",
    s10: "Ці умови регулюються законодавством Литовської Республіки та застосовними нормами ЄС.",
    s11h: "11. Контакти",
    s11: "Запитання? Напишіть нам: noctiraeai@gmail.com.",
  },
  zh: {
    back: "返回", title: "服务条款", updated: "最后更新：2025年3月",
    s1h: "1. 接受条款",
    s1: "访问或使用Noctirae即表示您同意受本服务条款约束。如果不同意，请勿使用本服务。",
    s2h: "2. 服务描述",
    s2: "Noctirae是一款基于AI的工具，为娱乐和个人反思提供梦境解析。服务提供免费和高级订阅级别。",
    s3h: "3. 重要免责声明",
    s3: "本服务提供的梦境解析由人工智能生成，仅供娱乐和个人反思使用。不构成医疗、心理或治疗建议。如有心理健康问题，请咨询专业医疗人员。",
    s4h: "4. 用户账户",
    s4a: "您必须年满16岁才能创建账户",
    s4b: "您负责维护账户安全",
    s4c: "注册时必须提供准确信息",
    s4d: "每人一个账户",
    s5h: "5. 可接受的使用",
    s5p: "您同意不会：",
    s5a: "提交非法、有害或攻击性内容",
    s5b: "尝试对AI系统进行逆向工程或滥用",
    s5c: "与他人共享账户",
    s5d: "将服务用于自动化或商业数据抓取",
    s6h: "6. 订阅与付款",
    s6a: "高级订阅通过Stripe每月计费",
    s6b: "您可随时在设置中取消订阅",
    s6c: "取消在当前计费周期结束时生效",
    s6d: "不提供部分计费期退款",
    s7h: "7. 您的内容",
    s7: "您保留提交的梦境内容的所有权。提交内容即表示您授予我们有限许可以处理该内容（包括发送给OpenAI解析）。我们不使用您的内容训练AI模型。",
    s8h: "8. 责任限制",
    s8: "Noctirae按\"现状\"提供。我们不对因使用服务产生的间接或附带损害负责。我们的总责任不超过您在过去12个月支付的金额。",
    s9h: "9. 终止",
    s9: "我们保留暂停或终止违反条款的账户的权利。您可随时在设置页面删除账户。",
    s10h: "10. 适用法律",
    s10: "本条款受立陶宛共和国法律和适用的欧盟法规管辖。",
    s11h: "11. 联系我们",
    s11: "有疑问？请联系我们：noctiraeai@gmail.com。",
  },
  ja: {
    back: "戻る", title: "利用規約", updated: "最終更新：2025年3月",
    s1h: "1. 利用規約の同意",
    s1: "Noctiræにアクセスまたは使用することにより、本利用規約に同意したものとみなされます。同意しない場合は、サービスをご利用にならないでください。",
    s2h: "2. サービスの説明",
    s2: "Noctiræは、エンターテインメントと個人の内省を目的とした夢の解釈を提供するAI搭載ツールです。無料プランとプレミアムサブスクリプションを提供しています。",
    s3h: "3. 重要な免責事項",
    s3: "本サービスが提供する夢の解釈はAIによって生成されたもので、エンターテインメントと個人の内省のみを目的としています。医療、心理、精神科、または治療的アドバイスを構成するものではありません。精神的健康に懸念がある場合は、資格のある医療専門家に相談してください。",
    s4h: "4. ユーザーアカウント",
    s4a: "アカウントを作成するには16歳以上である必要があります",
    s4b: "アカウントのセキュリティの維持はお客様の責任です",
    s4c: "登録時に正確な情報を提供する必要があります",
    s4d: "1人につき1アカウント",
    s5h: "5. 許容される使用",
    s5p: "以下のことに同意します：",
    s5a: "違法、有害、または攻撃的なコンテンツを送信しない",
    s5b: "AIシステムのリバースエンジニアリングや悪用を試みない",
    s5c: "アカウントを他者と共有しない",
    s5d: "自動化または商業的なスクレイピングにサービスを使用しない",
    s6h: "6. サブスクリプションと支払い",
    s6a: "プレミアムサブスクリプションはStripeで毎月請求されます",
    s6b: "設定からいつでもサブスクリプションをキャンセルできます",
    s6c: "キャンセルは現在の請求期間の終わりに有効になります",
    s6d: "部分的な請求期間の返金は提供されません",
    s7h: "7. お客様のコンテンツ",
    s7: "送信した夢のコンテンツの所有権はお客様に帰属します。コンテンツを送信することで、サービス提供の目的（OpenAIへの送信を含む）で処理するための限定ライセンスを付与します。お客様のコンテンツをAIモデルのトレーニングに使用しません。",
    s8h: "8. 責任の制限",
    s8: "Noctiræは「現状のまま」提供されます。サービスの使用から生じる間接的または結果的損害について責任を負いません。総責任額は過去12ヶ月にお支払いいただいた金額を超えないものとします。",
    s9h: "9. 終了",
    s9: "これらの規約に違反するアカウントを停止または終了する権利を留保します。設定ページからいつでもアカウントを削除できます。",
    s10h: "10. 準拠法",
    s10: "本規約はリトアニア共和国の法律および適用されるEU規制に準拠します。",
    s11h: "11. お問い合わせ",
    s11: "ご質問はこちら：noctiraeai@gmail.com",
  },
};

export default function TermsPage() {
  const locale = useLocale();
  const t = content[locale] ?? content.en;

  return (
    <div className="min-h-screen px-4 py-10 max-w-2xl mx-auto">
      <a
        href="/settings"
        className="inline-flex items-center gap-2 text-dream-500 hover:text-dream-300 text-sm mb-8 transition-colors"
      >
        <ArrowLeft size={16} /> {t.back}
      </a>

      <h1 className="text-2xl font-bold text-dream-100 mb-2">{t.title}</h1>
      <p className="text-dream-500 text-sm mb-8">{t.updated}</p>

      <div className="space-y-8 text-dream-300 text-sm leading-relaxed">
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s1h}</h2>
          <p>{t.s1}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s2h}</h2>
          <p>{t.s2}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s3h}</h2>
          <p className="p-3 rounded-xl bg-dream-900/40 border border-dream-800/30">{t.s3}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s4h}</h2>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s4a, t.s4b, t.s4c, t.s4d].map((item) => <li key={item}>{item}</li>)}
          </ul>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s5h}</h2>
          <p className="mb-3">{t.s5p}</p>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s5a, t.s5b, t.s5c, t.s5d].map((item) => <li key={item}>{item}</li>)}
          </ul>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s6h}</h2>
          <ul className="space-y-2 list-disc list-inside">
            {[t.s6a, t.s6b, t.s6c, t.s6d].map((item) => <li key={item}>{item}</li>)}
          </ul>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s7h}</h2>
          <p>{t.s7}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s8h}</h2>
          <p>{t.s8}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s9h}</h2>
          <p>{t.s9}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s10h}</h2>
          <p>{t.s10}</p>
        </section>
        <section>
          <h2 className="text-dream-200 font-semibold text-base mb-3">{t.s11h}</h2>
          <p>
            {t.s11.replace("noctiraeai@gmail.com", "")}{" "}
            <a href="mailto:noctiraeai@gmail.com" className="text-dream-400 hover:text-dream-200 underline">
              noctiraeai@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
